examples_url: https://github.com/0dayResearchLab/kafl.targets.git
examples_root: "{{ kafl_install_root }}/examples"

dvkm_sub_path: linux-user/dvkm/Damn_Vulnerable_Kernel_Module
linux_agent_sub_path: linux-user/linux_kafl_agent
